services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: phonex
      POSTGRES_PASSWORD: phonex
      POSTGRES_DB: phonex
    ports:
      - "5432:5432"
    volumes:
      - phonex_pg:/var/lib/postgresql/data

volumes:
  phonex_pg:
